### ISSUE TITLE
FE Detector hearbeat basic view

### ISSUE THREAD

**Issue by Fullbaro** [Kalamansanai/plm-client#42]

**Comment by bormilan** [comment]
@balint-szabox here is the BE implementation's issue: https://github.com/orgs/Kalamansanai/projects/9?pane=issue&itemId=24459893
we need a simple panel on the detector card, that displays the logs in a simple format.

**Comment by balint-szabox** [comment]
- Heartbeat data displayed on the front end.
-  It is not dynamically updated yet. 
- It was arranged in one table. 
- TimeStamp is created on the frontend.

Current looks of it:

![337295238_929242085195022_8315716278012572261_n](https://user-images.githubusercontent.com/70958880/229292666-985ccf05-74b5-4b4f-adb6-d23ee7f4f900.png)

**Comment by bormilan** [comment]
Merged.
It looks nice, but i have this wierd look: 

![Image](https://user-images.githubusercontent.com/71042542/229361484-1e07d2de-9e28-462d-af48-319288668509.png)

Pls look at it at monday and fix it.
